# Generated by Django 4.0.5 on 2022-07-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdbooksApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
