# Generated by Django 4.0.5 on 2022-07-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdbooksApp', '0004_usuario_edad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Lector',
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name_plural': 'LEctores'},
        ),
    ]
