# Generated by Django 4.0.5 on 2022-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdbooksApp', '0006_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatares'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name_plural': 'Lectores'},
        ),
        migrations.AddField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
