# Generated by Django 4.0.5 on 2022-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdbooksApp', '0007_alter_avatar_options_alter_lector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='portadas'),
        ),
    ]
